<?xml version="1.0" encoding="UTF-8" ?>
<!--
   Copyright 2005-2013 VMware, Inc.  All rights reserved.
-->
<definitions targetNamespace="urn:smsService"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:interface="urn:sms"
>
   <import location="sms.wsdl" namespace="urn:sms" />
   <service name="SmsService">
      <port binding="interface:SmsBinding" name="SmsPort">
         <soap:address location="https://localhost/sms/sdk" />
      </port>
   </service>
</definitions>
